#pragma once
#include "Global.h"
#include "State.h"

DEFINE_STATE(StartState)
END_DEFINE_STATE

DEFINE_STATE(InitiationState)
END_DEFINE_STATE

DEFINE_STATE(WaitActionState)
END_DEFINE_STATE

DEFINE_STATE(WaitOtherActionState)
END_DEFINE_STATE

DEFINE_STATE(ActState)
END_DEFINE_STATE

DEFINE_STATE(ProcessState)
	int flag;
END_DEFINE_STATE

DEFINE_STATE(DieState)
END_DEFINE_STATE

DEFINE_STATE(EffectState)
END_DEFINE_STATE

DEFINE_STATE(RebornState)
END_DEFINE_STATE

DEFINE_STATE(WinState)
END_DEFINE_STATE

DEFINE_STATE(LoseState)
END_DEFINE_STATE
